// Раскладки букв для телефона (5×9) по кадрам: кадр 0 — ролик, дальше 14 фото.
// Подобраны под каждое фото вместе с кадрированием (MOBILE_PHOTO_X): буквы не закрывают лица,
// занимают сетку по всей высоте, между соседними кадрами буква сдвигается не больше чем
// на одну клетку (сбоку, сверху или снизу). Свободна только клетка счётчика в нижнем ряду;
// свайп по нижнему ряду работает и поверх букв.

const TEXT = 'это люди,\nкоторые его\nсоздают';

export const MOBILE_FRAME_LAYOUTS = [
    [
        { x: 0, y: 0, type: 'img', src: 'WordS' },
        { x: 0, y: 1, type: 'img', src: 'WordO' },
        { x: 0, y: 2, type: 'img', src: 'WordU' },
        { x: 0, y: 3, type: 'img', src: 'WordT' },
        { x: 0, y: 4, type: 'img', src: 'WordH' },
        { x: 2, y: 6, type: 'img', src: 'WordU' },
        { x: 2, y: 7, type: 'img', src: 'WordU' },
        { x: 3, y: 7, type: 'img', src: 'WordU' },
        { x: 3, y: 8, type: 'img', src: 'WordB' },
        { x: 2, y: 4, type: 'text', text: TEXT, colSpan: 2 },
    ],
    [
        { x: 0, y: 0, type: 'img', src: 'WordS' },
        { x: 0, y: 1, type: 'img', src: 'WordO' },
        { x: 0, y: 2, type: 'img', src: 'WordU' },
        { x: 1, y: 3, type: 'img', src: 'WordT' },
        { x: 1, y: 4, type: 'img', src: 'WordH' },
        { x: 2, y: 6, type: 'img', src: 'WordU' },
        { x: 3, y: 7, type: 'img', src: 'WordU' },
        { x: 4, y: 7, type: 'img', src: 'WordU' },
        { x: 4, y: 8, type: 'img', src: 'WordB' },
        { x: 2, y: 5, type: 'text', text: TEXT, colSpan: 2 },
    ],
    [
        { x: 0, y: 0, type: 'img', src: 'WordS' },
        { x: 0, y: 1, type: 'img', src: 'WordO' },
        { x: 0, y: 2, type: 'img', src: 'WordU' },
        { x: 0, y: 3, type: 'img', src: 'WordT' },
        { x: 1, y: 4, type: 'img', src: 'WordH' },
        { x: 2, y: 6, type: 'img', src: 'WordU' },
        { x: 2, y: 7, type: 'img', src: 'WordU' },
        { x: 3, y: 7, type: 'img', src: 'WordU' },
        { x: 4, y: 8, type: 'img', src: 'WordB' },
        { x: 3, y: 5, type: 'text', text: TEXT, colSpan: 2 },
    ],
    [
        { x: 0, y: 0, type: 'img', src: 'WordS' },
        { x: 0, y: 1, type: 'img', src: 'WordO' },
        { x: 0, y: 2, type: 'img', src: 'WordU' },
        { x: 0, y: 3, type: 'img', src: 'WordT' },
        { x: 0, y: 4, type: 'img', src: 'WordH' },
        { x: 2, y: 6, type: 'img', src: 'WordU' },
        { x: 2, y: 7, type: 'img', src: 'WordU' },
        { x: 3, y: 7, type: 'img', src: 'WordU' },
        { x: 3, y: 8, type: 'img', src: 'WordB' },
        { x: 2, y: 5, type: 'text', text: TEXT, colSpan: 2 },
    ],
    [
        { x: 0, y: 0, type: 'img', src: 'WordS' },
        { x: 0, y: 1, type: 'img', src: 'WordO' },
        { x: 0, y: 2, type: 'img', src: 'WordU' },
        { x: 0, y: 3, type: 'img', src: 'WordT' },
        { x: 1, y: 4, type: 'img', src: 'WordH' },
        { x: 2, y: 6, type: 'img', src: 'WordU' },
        { x: 2, y: 7, type: 'img', src: 'WordU' },
        { x: 3, y: 7, type: 'img', src: 'WordU' },
        { x: 4, y: 8, type: 'img', src: 'WordB' },
        { x: 3, y: 5, type: 'text', text: TEXT, colSpan: 2 },
    ],
    [
        { x: 0, y: 0, type: 'img', src: 'WordS' },
        { x: 0, y: 1, type: 'img', src: 'WordO' },
        { x: 0, y: 2, type: 'img', src: 'WordU' },
        { x: 0, y: 3, type: 'img', src: 'WordT' },
        { x: 0, y: 4, type: 'img', src: 'WordH' },
        { x: 2, y: 6, type: 'img', src: 'WordU' },
        { x: 2, y: 7, type: 'img', src: 'WordU' },
        { x: 3, y: 7, type: 'img', src: 'WordU' },
        { x: 3, y: 8, type: 'img', src: 'WordB' },
        { x: 2, y: 5, type: 'text', text: TEXT, colSpan: 2 },
    ],
    [
        { x: 0, y: 0, type: 'img', src: 'WordS' },
        { x: 0, y: 1, type: 'img', src: 'WordO' },
        { x: 0, y: 2, type: 'img', src: 'WordU' },
        { x: 1, y: 3, type: 'img', src: 'WordT' },
        { x: 1, y: 4, type: 'img', src: 'WordH' },
        { x: 2, y: 6, type: 'img', src: 'WordU' },
        { x: 2, y: 7, type: 'img', src: 'WordU' },
        { x: 3, y: 7, type: 'img', src: 'WordU' },
        { x: 4, y: 8, type: 'img', src: 'WordB' },
        { x: 3, y: 5, type: 'text', text: TEXT, colSpan: 2 },
    ],
    [
        { x: 0, y: 1, type: 'img', src: 'WordS' },
        { x: 1, y: 1, type: 'img', src: 'WordO' },
        { x: 1, y: 2, type: 'img', src: 'WordU' },
        { x: 1, y: 3, type: 'img', src: 'WordT' },
        { x: 1, y: 4, type: 'img', src: 'WordH' },
        { x: 2, y: 6, type: 'img', src: 'WordU' },
        { x: 2, y: 7, type: 'img', src: 'WordU' },
        { x: 3, y: 7, type: 'img', src: 'WordU' },
        { x: 3, y: 8, type: 'img', src: 'WordB' },
        { x: 2, y: 5, type: 'text', text: TEXT, colSpan: 2 },
    ],
    [
        { x: 0, y: 2, type: 'img', src: 'WordS' },
        { x: 1, y: 2, type: 'img', src: 'WordO' },
        { x: 1, y: 3, type: 'img', src: 'WordU' },
        { x: 1, y: 4, type: 'img', src: 'WordT' },
        { x: 1, y: 5, type: 'img', src: 'WordH' },
        { x: 2, y: 6, type: 'img', src: 'WordU' },
        { x: 2, y: 7, type: 'img', src: 'WordU' },
        { x: 3, y: 7, type: 'img', src: 'WordU' },
        { x: 4, y: 8, type: 'img', src: 'WordB' },
        { x: 3, y: 5, type: 'text', text: TEXT, colSpan: 2 },
    ],
    [
        { x: 0, y: 3, type: 'img', src: 'WordS' },
        { x: 1, y: 3, type: 'img', src: 'WordO' },
        { x: 1, y: 4, type: 'img', src: 'WordU' },
        { x: 1, y: 5, type: 'img', src: 'WordT' },
        { x: 1, y: 6, type: 'img', src: 'WordH' },
        { x: 2, y: 6, type: 'img', src: 'WordU' },
        { x: 2, y: 7, type: 'img', src: 'WordU' },
        { x: 3, y: 7, type: 'img', src: 'WordU' },
        { x: 3, y: 8, type: 'img', src: 'WordB' },
        { x: 3, y: 5, type: 'text', text: TEXT, colSpan: 2 },
    ],
    [
        { x: 0, y: 2, type: 'img', src: 'WordS' },
        { x: 0, y: 3, type: 'img', src: 'WordO' },
        { x: 0, y: 4, type: 'img', src: 'WordU' },
        { x: 0, y: 5, type: 'img', src: 'WordT' },
        { x: 1, y: 6, type: 'img', src: 'WordH' },
        { x: 2, y: 6, type: 'img', src: 'WordU' },
        { x: 2, y: 7, type: 'img', src: 'WordU' },
        { x: 3, y: 7, type: 'img', src: 'WordU' },
        { x: 4, y: 8, type: 'img', src: 'WordB' },
        { x: 3, y: 6, type: 'text', text: TEXT, colSpan: 2 },
    ],
    [
        { x: 0, y: 1, type: 'img', src: 'WordS' },
        { x: 0, y: 2, type: 'img', src: 'WordO' },
        { x: 0, y: 3, type: 'img', src: 'WordU' },
        { x: 0, y: 4, type: 'img', src: 'WordT' },
        { x: 1, y: 5, type: 'img', src: 'WordH' },
        { x: 2, y: 6, type: 'img', src: 'WordU' },
        { x: 2, y: 7, type: 'img', src: 'WordU' },
        { x: 3, y: 7, type: 'img', src: 'WordU' },
        { x: 3, y: 8, type: 'img', src: 'WordB' },
        { x: 3, y: 5, type: 'text', text: TEXT, colSpan: 2 },
    ],
    [
        { x: 0, y: 0, type: 'img', src: 'WordS' },
        { x: 0, y: 1, type: 'img', src: 'WordO' },
        { x: 0, y: 2, type: 'img', src: 'WordU' },
        { x: 0, y: 3, type: 'img', src: 'WordT' },
        { x: 1, y: 4, type: 'img', src: 'WordH' },
        { x: 2, y: 6, type: 'img', src: 'WordU' },
        { x: 2, y: 7, type: 'img', src: 'WordU' },
        { x: 3, y: 7, type: 'img', src: 'WordU' },
        { x: 4, y: 8, type: 'img', src: 'WordB' },
        { x: 2, y: 5, type: 'text', text: TEXT, colSpan: 2 },
    ],
    [
        { x: 0, y: 0, type: 'img', src: 'WordS' },
        { x: 0, y: 1, type: 'img', src: 'WordO' },
        { x: 0, y: 2, type: 'img', src: 'WordU' },
        { x: 0, y: 3, type: 'img', src: 'WordT' },
        { x: 0, y: 4, type: 'img', src: 'WordH' },
        { x: 2, y: 6, type: 'img', src: 'WordU' },
        { x: 2, y: 7, type: 'img', src: 'WordU' },
        { x: 3, y: 7, type: 'img', src: 'WordU' },
        { x: 3, y: 8, type: 'img', src: 'WordB' },
        { x: 3, y: 5, type: 'text', text: TEXT, colSpan: 2 },
    ],
    [
        { x: 0, y: 0, type: 'img', src: 'WordS' },
        { x: 0, y: 1, type: 'img', src: 'WordO' },
        { x: 0, y: 2, type: 'img', src: 'WordU' },
        { x: 0, y: 3, type: 'img', src: 'WordT' },
        { x: 1, y: 4, type: 'img', src: 'WordH' },
        { x: 2, y: 6, type: 'img', src: 'WordU' },
        { x: 2, y: 7, type: 'img', src: 'WordU' },
        { x: 3, y: 7, type: 'img', src: 'WordU' },
        { x: 4, y: 8, type: 'img', src: 'WordB' },
        { x: 2, y: 5, type: 'text', text: TEXT, colSpan: 2 },
    ],
];

// object-position по горизонтали для фото на телефоне (кадр 0 — ролик)
export const MOBILE_PHOTO_X = ['50%', '50%', '30%', '30%', '50%', '30%', '45%', '75%', '45%', '80%', '25%', '50%', '55%', '30%', '40%'];
